name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install and test server
      - name: Install server dependencies
        run: |
          cd server
          npm install
      - name: Lint server
        run: |
          cd server
          npm run lint || echo "No lint script"
      - name: Test server
        run: |
          cd server
          npm test || echo "No test script"

      # Install and test client
      - name: Install client dependencies
        run: |
          cd client
          npm install
      - name: Lint client
        run: |
          cd client
          npm run lint || echo "No lint script"
      - name: Test client
        run: |
          cd client
          npm test || echo "No test script"
      - name: Build client
        run: |
          cd client
          npm run build

  # Optional: Deploy job (uncomment and configure for your deployment target)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Vercel
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         working-directory: ./client
  #         prod: ${{ github.ref == 'refs/heads/main' }} 